config/routes.rb
Rails.application.routes.draw do
  resources :blog_livros
  get 'home/index'
  root 'home#index'
  resources :posts
  get "/articles", to: "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_livro.rb
class BlogLivro < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :description, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/blog_livros_controller.rb
class BlogLivrosController < ApplicationController
  before_action :set_blog_livro, only: %i[ show edit update destroy ]

  # GET /blog_livros or /blog_livros.json
  def index
    @blog_livros = BlogLivro.all
  end

  # GET /blog_livros/1 or /blog_livros/1.json
  def show
  end

  # GET /blog_livros/new
  def new
    @blog_livro = BlogLivro.new
  end

  # GET /blog_livros/1/edit
  def edit
  end

  # POST /blog_livros or /blog_livros.json
  def create
    @blog_livro = BlogLivro.new(blog_livro_params)

    respond_to do |format|
      if @blog_livro.save
        format.html { redirect_to blog_livro_url(@blog_livro), notice: "Blog livro was successfully created." }
        format.json { render :show, status: :created, location: @blog_livro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog_livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_livros/1 or /blog_livros/1.json
  def update
    respond_to do |format|
      if @blog_livro.update(blog_livro_params)
        format.html { redirect_to blog_livro_url(@blog_livro), notice: "Blog livro was successfully updated." }
        format.json { render :show, status: :ok, location: @blog_livro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog_livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_livros/1 or /blog_livros/1.json
  def destroy
    @blog_livro.destroy!

    respond_to do |format|
      format.html { redirect_to blog_livros_url, notice: "Blog livro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_livro
      @blog_livro = BlogLivro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_livro_params
      params.require(:blog_livro).permit(:tittle, :author, :noteforthebook, :int, :description, :text)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_livros_helper.rb
module BlogLivrosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/index.html.erb
<h1>Hello, Rails!</h1>

app/views/blog_livros/_blog_livro.html.erb
<div id="<%= dom_id blog_livro %>">
  <p>
    <strong>Titulo:</strong>
    <%= blog_livro.tittle %>
  </p>

  <p>
    <strong>Autor:</strong>
    <%= blog_livro.author %>
  </p>

  <p>
    <strong>Nota para o livro :</strong>
    <%= blog_livro.noteforthebook %>
  </p>

  
  <p>
    <strong>Descrição:</strong>
    <%= blog_livro.description %>
  </p>
  

</div>

app/views/blog_livros/_form.html.erb
<%= form_with(model: blog_livro) do |form| %>
  <% if blog_livro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog_livro.errors.count, "error") %> prohibited this blog_livro from being saved:</h2>

      <ul>
        <% blog_livro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Titulo, style: "display: block" %>
    <%= form.text_field :tittle %>
  </div>

  <div>
    <%= form.label :Autor, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :Nota_Livro, style: "display: block" %>
    <%= form.text_field :noteforthebook %>
  </div>

  <div>
    <%= form.label :Descrição, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_livros/edit.html.erb
<h1>Editando resenha sobre Livro</h1>

<%= render "form", blog_livro: @blog_livro %>

<br>

<div>
  <%= link_to "Mostrar resenhas sobre livros", @blog_livro %> |
  <%= link_to "voltar par o blog livros", blog_livros_path %>
</div>

app/views/blog_livros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blog livros</h1>

<div id="blog_livros">
  <% @blog_livros.each do |blog_livro| %>
    <%= render blog_livro %>
    <p>
      <%= link_to "Show this blog livro", blog_livro %>
    </p>
  <% end %>
</div>

<%= link_to "Resenha sobre livro", new_blog_livro_path %>

app/views/blog_livros/new.html.erb
<h1>Nova resenha sobre livro</h1>

<%= render "form", blog_livro: @blog_livro %>

<br>

<div>
  <%= link_to "Voltar para blog livros", blog_livros_path %>
</div>

app/views/blog_livros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog_livro %>

<div>
  <%= link_to "Editar resenha sobre livro", edit_blog_livro_path(@blog_livro) %> |
  <%= link_to "Voltar para pág inicial", blog_livros_path %>

  <%= button_to "Excluir resenha", @blog_livro, method: :delete %>
</div>

app/views/home/index.html.erb
<h1>Pedrinho Henrique</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= post.text %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts Pedrinho</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>